# Generated by Django 4.2.30 on 2026-06-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='num_questions',
            field=models.IntegerField(default=5),
        ),
    ]
