# Generated by Django 6.0.5 on 2026-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_interview_num_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('recruiter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('jd_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('resume_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('report_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
